_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.12.10
            "5": 0.18.7
            "6": 4.49.0
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
