_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
                - 71
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.10
            "5": 0.18.7
            "6": 4.49.0
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
architecture:
    value: DETR-ResNet50
classes:
    value:
        - Human
        - Car
        - Truck
        - Van
        - Motorbike
        - Bicycle
        - Bus
        - Trailer
dataset:
    value: AU-AIR
img_size:
    value: 800
max_size:
    value: 1333
