_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 80
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 80
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.10
            "5": 0.18.7
            "6": 4.49.0
            "8":
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
backbone_lr:
    value: 0.0005
batch_size:
    value: 4
epochs:
    value: 10
learning_rate:
    value: 5e-05
