_wandb:
    value:
        bounding_box/class_labels:
            prediction_wandb_delimeter_predictions:
                key: prediction_wandb_delimeter_predictions
                type: bounding_box/class_labels
                value:
                    "1": class_1
                    "2": class_2
                    "3": class_3
                    "4": class_4
                    "5": class_5
                    "6": class_6
                    "7": class_7
                    "8": class_8
        cli_version: 0.18.7
        m: []
        python_version: 3.12.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 71
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.12.10
            "5": 0.18.7
            "6": 4.49.0
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
